Página serviços
Jovens-do-futuro/website pull request #19
Opened 2024-06-09 19:22 UTC by AndreCcerq

![image](https://github.com/Jovens-do-futuro/website/assets/160081017/118bd148-1166-4eda-a13e-dd3324b11133)

2024-06-09 20:26 UTC, PedroFnseca requested changes

2024-06-09 20:26 UTC, PedroFnseca commented on global.css
> -  --blue-light: #01c2ff;
tem que alterar no arquivo que ta usando `--blue-light` tb que é no `style.css` que está na raiz do projeto

2024-06-11 23:58 UTC, luizbrito6 approved these changes

2024-06-12 00:07 UTC, EduLeal approved these changes

2024-06-12 00:57 UTC, PedroFnseca approved these changes

2024-06-12 00:58 UTC, PedroFnseca requested changes

2024-06-12 00:58 UTC, PedroFnseca commented on global.css
> +  /* color: var(--black); */
desacomentar

2024-06-12 01:01 UTC, PedroFnseca approved these changes

2024-06-12 01:01 UTC, PedroFnseca commented on global.css
> +  --green-light: #63fad1;
aqui ta duplicado

2024-06-12 01:01 UTC, merged